spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: joao
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

graphql:
  servlet:
    corsEnabled: true
    enabled: true
    mapping: '/graphql'